.........................................FF...............................EE.EEFEEEEFF.FFFFFFF
======================================================================
ERROR: test_1 (unit_tests.unit_tests_TopoSearchParallel.TopoSearchParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearchParallel.py", line 25, in test_1
    best_tree,max_score,best_params = myTopoSearch_EM.search(maxiter=200,nreps=1,verbose=False)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 101, in search
    trees,score,params = self.__search_one__(strategy,maxiter=maxiter,verbose=verbose,only_marked=False,checkpoint_file=checkpoint_file)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 146, in __search_one__
    new_score,n_attempts,success = self.single_nni(curr_score,nni_iter,strategy,only_marked=only_marked)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search_parallel.py", line 62, in single_nni
    return new_score,curr_end_idx,took
UnboundLocalError: local variable 'new_score' referenced before assignment

======================================================================
ERROR: test_10 (unit_tests.unit_tests_TopoSearchParallel.TopoSearchParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearchParallel.py", line 197, in test_10
    best_tree,max_score,best_params = myTopoSearch.search(maxiter=200,verbose=False,strategy=my_strategy,nreps=1)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 101, in search
    trees,score,params = self.__search_one__(strategy,maxiter=maxiter,verbose=verbose,only_marked=False,checkpoint_file=checkpoint_file)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 146, in __search_one__
    new_score,n_attempts,success = self.single_nni(curr_score,nni_iter,strategy,only_marked=only_marked)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search_parallel.py", line 62, in single_nni
    return new_score,curr_end_idx,took
UnboundLocalError: local variable 'new_score' referenced before assignment

======================================================================
ERROR: test_3 (unit_tests.unit_tests_TopoSearchParallel.TopoSearchParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearchParallel.py", line 60, in test_3
    best_tree,max_score,best_params = myTopoSearch.search(maxiter=200,verbose=False,nreps=1)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 101, in search
    trees,score,params = self.__search_one__(strategy,maxiter=maxiter,verbose=verbose,only_marked=False,checkpoint_file=checkpoint_file)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 146, in __search_one__
    new_score,n_attempts,success = self.single_nni(curr_score,nni_iter,strategy,only_marked=only_marked)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search_parallel.py", line 62, in single_nni
    return new_score,curr_end_idx,took
UnboundLocalError: local variable 'new_score' referenced before assignment

======================================================================
ERROR: test_4 (unit_tests.unit_tests_TopoSearchParallel.TopoSearchParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearchParallel.py", line 79, in test_4
    best_tree,max_score,best_params = myTopoSearch.search(maxiter=200,verbose=False,strategy=my_strategy,nreps=1)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 89, in search
    trees,score,params = self.__search_one__(strategy,maxiter=maxiter,verbose=verbose,only_marked=True,checkpoint_file=checkpoint_file)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 146, in __search_one__
    new_score,n_attempts,success = self.single_nni(curr_score,nni_iter,strategy,only_marked=only_marked)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search_parallel.py", line 62, in single_nni
    return new_score,curr_end_idx,took
UnboundLocalError: local variable 'new_score' referenced before assignment

======================================================================
ERROR: test_6 (unit_tests.unit_tests_TopoSearchParallel.TopoSearchParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearchParallel.py", line 121, in test_6
    best_tree,max_score,best_params = myTopoSearch.search(maxiter=200,verbose=False,strategy=my_strategy,nreps=1)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 101, in search
    trees,score,params = self.__search_one__(strategy,maxiter=maxiter,verbose=verbose,only_marked=False,checkpoint_file=checkpoint_file)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 146, in __search_one__
    new_score,n_attempts,success = self.single_nni(curr_score,nni_iter,strategy,only_marked=only_marked)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search_parallel.py", line 62, in single_nni
    return new_score,curr_end_idx,took
UnboundLocalError: local variable 'new_score' referenced before assignment

======================================================================
ERROR: test_7 (unit_tests.unit_tests_TopoSearchParallel.TopoSearchParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearchParallel.py", line 142, in test_7
    best_tree,max_score,best_params = myTopoSearch.search(maxiter=200,verbose=False,strategy=my_strategy,nreps=1)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 89, in search
    trees,score,params = self.__search_one__(strategy,maxiter=maxiter,verbose=verbose,only_marked=True,checkpoint_file=checkpoint_file)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 146, in __search_one__
    new_score,n_attempts,success = self.single_nni(curr_score,nni_iter,strategy,only_marked=only_marked)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search_parallel.py", line 62, in single_nni
    return new_score,curr_end_idx,took
UnboundLocalError: local variable 'new_score' referenced before assignment

======================================================================
ERROR: test_8 (unit_tests.unit_tests_TopoSearchParallel.TopoSearchParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearchParallel.py", line 161, in test_8
    best_tree,max_score,best_params = myTopoSearch.search(maxiter=200,verbose=False,strategy=my_strategy,nreps=1)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 89, in search
    trees,score,params = self.__search_one__(strategy,maxiter=maxiter,verbose=verbose,only_marked=True,checkpoint_file=checkpoint_file)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 146, in __search_one__
    new_score,n_attempts,success = self.single_nni(curr_score,nni_iter,strategy,only_marked=only_marked)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search_parallel.py", line 62, in single_nni
    return new_score,curr_end_idx,took
UnboundLocalError: local variable 'new_score' referenced before assignment

======================================================================
ERROR: test_9 (unit_tests.unit_tests_TopoSearchParallel.TopoSearchParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearchParallel.py", line 180, in test_9
    best_tree,max_score,best_params = myTopoSearch.search(maxiter=200,verbose=False,strategy=my_strategy,nreps=1)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 101, in search
    trees,score,params = self.__search_one__(strategy,maxiter=maxiter,verbose=verbose,only_marked=False,checkpoint_file=checkpoint_file)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search.py", line 146, in __search_one__
    new_score,n_attempts,success = self.single_nni(curr_score,nni_iter,strategy,only_marked=only_marked)
  File "/Users/gary/Documents/Projects/spalin/problin/problin_libs/Topology_search_parallel.py", line 62, in single_nni
    return new_score,curr_end_idx,took
UnboundLocalError: local variable 'new_score' referenced before assignment

======================================================================
FAIL: test_47 (unit_tests.unit_tests_EMSolver.EMTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_EMSolver.py", line 557, in test_47
    self.assertAlmostEqual(0,abs(true_nllh-nllh)/true_nllh,places=4,msg="EMTest: test_47 failed.")
AssertionError: 0 != 0.2952484316236502 within 4 places (0.2952484316236502 difference) : EMTest: test_47 failed.

======================================================================
FAIL: test_48 (unit_tests.unit_tests_EMSolver.EMTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_EMSolver.py", line 590, in test_48
    self.assertAlmostEqual(abs(true_nllh-nllh)/true_nllh,0,places=4,msg="EMTest: test_48 failed.")
AssertionError: 0.5177901659845234 != 0 within 4 places (0.5177901659845234 difference) : EMTest: test_48 failed.

======================================================================
FAIL: test_5 (unit_tests.unit_tests_TopoSearchParallel.TopoSearchParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearchParallel.py", line 103, in test_5
    self.assertAlmostEqual(nllh_bf,nllh_nni,places=4,msg="TopoSearchTest: test_5 failed.")
AssertionError: 12.48204978089449 != 17.40752474816076 within 4 places (4.92547496726627 difference) : TopoSearchTest: test_5 failed.

======================================================================
FAIL: test_1 (unit_tests.unit_tests_TopoSearch.TopoSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearch.py", line 81, in test_1
    self.assertAlmostEqual(nllh_bf,nllh_nni_EM,places=4,msg="TopoSearchTest: test_1 failed.")
AssertionError: 7.877269958604131 != 14.447811982567456 within 4 places (6.570542023963325 difference) : TopoSearchTest: test_1 failed.

======================================================================
FAIL: test_10 (unit_tests.unit_tests_TopoSearch.TopoSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearch.py", line 253, in test_10
    self.assertAlmostEqual(nllh_bf,nllh_nni,places=4,msg="TopoSearchTest: test_10 failed.")
AssertionError: 7.0063474330891236 != 20.696958921893458 within 4 places (13.690611488804334 difference) : TopoSearchTest: test_10 failed.

======================================================================
FAIL: test_3 (unit_tests.unit_tests_TopoSearch.TopoSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearch.py", line 116, in test_3
    self.assertAlmostEqual(nllh_bf,nllh_nni,places=4,msg="TopoSearchTest: test_3 failed.")
AssertionError: 7.877269958604131 != 16.214960680704795 within 4 places (8.337690722100664 difference) : TopoSearchTest: test_3 failed.

======================================================================
FAIL: test_4 (unit_tests.unit_tests_TopoSearch.TopoSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearch.py", line 135, in test_4
    self.assertAlmostEqual(nllh_bf,nllh_nni,places=4,msg="TopoSearchTest: test_4 failed.")
AssertionError: 7.877269958604131 != 13.43096904825739 within 4 places (5.553699089653259 difference) : TopoSearchTest: test_4 failed.

======================================================================
FAIL: test_5 (unit_tests.unit_tests_TopoSearch.TopoSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearch.py", line 156, in test_5
    self.assertAlmostEqual(nllh_bf,nllh_nni,places=4,msg="TopoSearchTest: test_5 failed.")
AssertionError: 12.48204978089449 != 21.6797906853437 within 4 places (9.19774090444921 difference) : TopoSearchTest: test_5 failed.

======================================================================
FAIL: test_6 (unit_tests.unit_tests_TopoSearch.TopoSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearch.py", line 178, in test_6
    self.assertAlmostEqual(nllh_bf,nllh_nni,places=4,msg="TopoSearchTest: test_6 failed.")
AssertionError: 6.042549046654788 != 24.493024527599438 within 4 places (18.45047548094465 difference) : TopoSearchTest: test_6 failed.

======================================================================
FAIL: test_7 (unit_tests.unit_tests_TopoSearch.TopoSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearch.py", line 198, in test_7
    self.assertAlmostEqual(nllh_bf,nllh_nni,places=4,msg="TopoSearchTest: test_7 failed.")
AssertionError: 12.010496077449595 != 21.7675696014442 within 4 places (9.757073523994606 difference) : TopoSearchTest: test_7 failed.

======================================================================
FAIL: test_8 (unit_tests.unit_tests_TopoSearch.TopoSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearch.py", line 216, in test_8
    self.assertAlmostEqual(nllh_bf,nllh_nni,places=4,msg="TopoSearchTest: test_8 failed.")
AssertionError: 12.010496077449595 != 22.346728071307194 within 4 places (10.336231993857599 difference) : TopoSearchTest: test_8 failed.

======================================================================
FAIL: test_9 (unit_tests.unit_tests_TopoSearch.TopoSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gary/Documents/Projects/spalin/problin/unit_tests/unit_tests_TopoSearch.py", line 235, in test_9
    self.assertAlmostEqual(nllh_bf,nllh_nni,places=4,msg="TopoSearchTest: test_9 failed.")
AssertionError: 7.0063474330891236 != 26.757701175557184 within 4 places (19.751353742468062 difference) : TopoSearchTest: test_9 failed.

----------------------------------------------------------------------
Ran 94 tests in 53.139s

FAILED (failures=12, errors=8)
